spring.application.name=customer-management-api
spring.jpa.defer-datasource-initialization=true

# External score service
score.api.base-url=${SCORE_API_BASE_URL:http://localhost:8081}
score.api.connect-timeout-ms=${SCORE_API_CONNECT_TIMEOUT_MS:3000}
score.api.read-timeout-ms=${SCORE_API_READ_TIMEOUT_MS:5000}